# Generated by Django 3.1.4 on 2021-01-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_adress1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_adress2',
            new_name='street_address2',
        ),
    ]
