# Generated by Django 3.1.4 on 2021-01-18 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chest_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bust_height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bust_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hip_circ1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hip_circ2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('back_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('back_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chest_circ', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_custom', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fabrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_made.fabric')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
