# Generated by Django 3.1.4 on 2021-01-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_made', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='friendly_name',
        ),
        migrations.AddField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fabric',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
