# Generated by Django 3.1.4 on 2021-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_made', '0002_auto_20210118_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='back_length',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='back_width',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='bust_height',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='bust_length',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='chest_circ',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='chest_width',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='hip_circ1',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='hip_circ2',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='shoulder_width',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
    ]
