# Generated by Django 3.1.4 on 2021-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_made', '0003_auto_20210118_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='extra_info',
            field=models.TextField(default=False, max_length=200),
        ),
    ]
