# Generated by Django 3.1.4 on 2021-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_made', '0005_auto_20210118_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='extra_info',
            field=models.TextField(max_length=200),
        ),
    ]
