# Generated by Django 3.1.4 on 2021-01-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_made', '0007_auto_20210119_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='fabrics',
        ),
        migrations.DeleteModel(
            name='Fabric',
        ),
    ]
