# Generated by Django 3.1.4 on 2021-01-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_made', '0009_remove_customproduct_price_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='select_fabric',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
