# Generated by Django 3.1.4 on 2021-02-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0001_initial'),
        ('custom_made', '0010_customproduct_select_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='fabrics.fabric'),
        ),
    ]
