# Generated by Django 3.1.4 on 2021-02-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_select_fabric'),
        ('custom_made', '0012_auto_20210205_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.product'),
        ),
    ]
