# Generated by Django 3.1.4 on 2021-01-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210105_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_custom',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
    ]
