# Generated by Django 3.1.4 on 2021-01-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='select_fabric',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
