# Generated by Django 3.1.4 on 2021-01-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_select_fabric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='select_fabric',
        ),
    ]
