# Generated by Django 3.1.4 on 2021-02-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_select_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_made',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
