# Generated by Django 3.1.4 on 2021-02-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_custom_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_made',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_custom',
        ),
    ]
